#!/bin/bash

# -k : kmersize
# -t : topcount
# -f :inputfile
source printtop.sh
executable="./main.exe"

if [ ! -f $executable ];then
	echo "No executable found. Did you compile the program?"
	exit
fi



OS=`uname`
if [ "$OS" == "Linux" ];then
  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./external/install/libbf/lib/
else
  export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:./external/install/libbf/lib/
fi




usage() { echo "Usage: $0 [-k <kmersize>] [-t <topcount>] [ -f <filename>]" 1>&2; exit 1; }

while getopts ":k:t:f:" o; do
    case "${o}" in
        k)
            k=${OPTARG}
            ;;
        t)
            t=${OPTARG}
	    ;;
	f)
	    f=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${k}" ] || [ -z "${t}" ] || [ -z "${f}" ]; then
    usage
fi

if [ ! -f "${f}" ];then
	echo "File"  "${f}" "not found!"
	exit
fi

ofile=`basename "${f}"`.OUT
$executable -f "${f}" -k "${k}" -t "${t}" | sort -n -k2 -r >  $ofile

printtop $ofile "${t}"
